//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using Olwen_2._0._0.DependencyInjection;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderHeaders = new HashSet<OrderHeader>();
        }
    
        public int CusID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Email { get; set; }
        public Nullable<int> Kind { get; set; }
        public byte[] Avatar { get; set; }

        public BitmapImage Image
        {
            get
            {
                return Avatar.LoadImage();
            }
            set
            {
                Avatar = value.ConvertToByte();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderHeader> OrderHeaders { get; set; }
    }
}
