//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingDetail
    {
        public Nullable<int> ProductId { get; set; }
        public int PurId { get; set; }
        public int PurDetailId { get; set; }
        public Nullable<int> PurQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> StoreID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Store Store { get; set; }
        public virtual PurchasingHeader PurchasingHeader { get; set; }
    }
}
