//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasingHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchasingHeader()
        {
            this.PurchasingDetails = new HashSet<PurchasingDetail>();
        }
    
        public int PurID { get; set; }
        public Nullable<int> SuplierID { get; set; }
        public Nullable<System.DateTime> PurDate { get; set; }
        public Nullable<int> LogID { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Logistic Logistic { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasingDetail> PurchasingDetails { get; set; }
    }
}
