//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryInfo
    {
        public int EmpID { get; set; }
        public Nullable<System.DateTime> DateSalary { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SalaryPay { get; set; }
        public int Num { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
