//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olwen_2._0._0.Model
{
    using Olwen_2._0._0.DependencyInjection;
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.PurchasingHeaders = new HashSet<PurchasingHeader>();
        }
    
        public int SupID { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Delegate { get; set; }
        public byte[] Avatar { get; set; }

        public BitmapImage Image
        {
            get
            {
                return Avatar.LoadImage();
            }
            set
            {
                Avatar = value.ConvertToByte();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchasingHeader> PurchasingHeaders { get; set; }
    }
}
